---
title: "Web Search Tools en Docker"
description: 
  Cómo ejecutar SearXNG en docker.
author:
  - name: José R Sosa
    url: https://josersosa.github.io/personalweb/
date: 03-30-2025
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
#    toc_float: false
categories:
  - n8n
  - Docker
  - HomeLab
preview: ../../images/workflow_n8n.png
draft: true
---

### Fuentes:
- Video:  [Upgrade Your AI Using Web Search](https://www.youtube.com/watch?v=GMlSFIp1na0) 
- Repo: [SearXNG](https://github.com/searxng/searxng) 
- Webpage: https://docs.searxng.org/
- [searxng-docker](https://github.com/searxng/searxng-docker)

## Ejecutando SearXNG en Docker

1. Podemos ejecutar SearXNG en docker con el siguiente coomando:

```bash
cd /usr/local
git clone https://github.com/searxng/searxng-docker.git
cd searxng-docker
```

2. Luego 3edite el archivo [.env](https://github.com/searxng/searxng-docker/blob/master/.env) para configurar el nombre de host y un correo electrónico
3. Generar la clave secreta `sed -i "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml`  
    En una Mac:`sed -i '' "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml`
    Los usuarios de Windows pueden usar el siguiente script de PowerShell para generar la clave secreta:
```powershell
$randomBytes = New-Object byte[] 32
(New-Object Security.Cryptography.RNGCryptoServiceProvider).GetBytes($randomBytes)
$secretKey = -join ($randomBytes | ForEach-Object { "{0:x2}" -f $_ })
(Get-Content searxng/settings.yml) -replace 'ultrasecretkey', $secretKey | Set-Content searxng/settings.yml
```
4. Edite [searxng/settings.yml](https://github.com/searxng/searxng-docker/blob/master/searxng/settings.yml) según sus necesidades
5. 6. Ejecute SearXNG en segundo plano:`docker compose up -d`

## Solución de problemas: cómo acceder a los registros

Para acceder a los registros de todos los contenedores utilice: `docker compose logs -f`.
Para acceder a los registros de un contenedor específico:
- Caddie:`docker compose logs -f caddy`
- BuscarXNG:`docker compose logs -f searxng`
- Valkyrie:`docker compose logs -f redis`
## Usando instancias disponibles en línea

hay una lista de instancias disponibles para el uso de servicios SearXNG aquí: https://searx.space/
